- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- README.md
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
- infrastructure/variables.tf
- package.json
- sonar-project.properties
Initial application setup. Naming and environment.
> Initial application setup

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
> update add hostname settings

- infrastructure/main.tf
- infrastructure/output.tf
> [PREVIEW] update vault settings

- app.js
- assets/scss/main.scss
- common/content.json
- middleware/setLocalsMiddleware.js
- package.json
- resources/mock.json
- steps/respond/Respond.html
- test/unit/middleware/ccd.test.js
- test/unit/middleware/setLocalsMiddleware.test.js
- views/includes/propositional_navigation.html
- views/page.njk
- yarn.lock
Fixes for respondent step layout
Fixes # 3100
Locally, unit and e2e testing
> [PREVIEW] Fixes for respondent step layout

- common/content.json
- steps/respond/Respond.html
- steps/review-application/ReviewApplication.html
- steps/start/Start.html
- views/page.njk
This makes back button to be displayed only on steps where it is needed
> [PREVIEW] fix back button bug

- .nsprc
- package.json
- yarn.lock
To fix build issue and not reference a specific commit
> Update one-per-page and one-per-page-test-suite to the latest

- app.js
- config/custom-environment-variables.yml
- config/default.yml
- package.json
The default page load timeout is 50ms which is too short and causing our tests/env to fail with 500s
Jenkins
> Increase timeouts

- infrastructure/prod.tfvars
Idam url change
* Hardware:
* JDK:
> Idam Url Change

- infrastructure/prod.tfvars
> Remove unnecessary port

- package.json
- steps/review-application/ReviewApplication.html
- test/unit/steps/reviewApplication.test.js
- yarn.lock
To ensure tests are running properly.
> [PREVIEW] Updated one-per-page-test-suite to the latest version

- package.json
- test/e2e/codecept.conf.js
* Archive html report
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
> * Remove unused reports

- app.js
- assets/scss/_legal-proceedings.scss
- assets/scss/main.scss
- config/default.yml
- steps/choose-a-response/ChooseAResponse.step.js
- steps/jurisdiction/Jurisdiction.content.json
- steps/jurisdiction/Jurisdiction.html
- steps/jurisdiction/Jurisdiction.step.js
- steps/legal-proceedings/LegalProceedings.html
- test/e2e/pages/jurisdiction.step.js
- test/e2e/paths/happyPath.js
- test/unit/steps/chooseAResponse.test.js
- test/unit/steps/jurisdiction.test.js
Jurisdiction Page
* Hardware:
* JDK:
> [PREVIEW] Jurisdiction

- steps/choose-a-response/ChooseAResponse.html
- steps/choose-a-response/ChooseAResponse.step.js
- test/unit/steps/chooseAResponse.test.js
Fix defend step bug
Fixes # DIV-3368
Tested locally, unit test.
> [PREVIEW] Fix defend step bug

- infrastructure/main.tf
Use Shared app service
User Shared App Services
* Hardware:
* JDK:
> [PREVIEW] User Shared App Services

- config/default.yml
- middleware/petitionMiddleware.js
- mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yesAdultery.mock
- mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
- mocks/steps/idamLogin/IdamLogin.content.json
- mocks/steps/idamLogin/IdamLogin.step.js
- mocks/steps/idamLogin/IdamLogin.template.html
- package.json
- steps/admit-adultery/AdmitAdultery.content.json
- steps/admit-adultery/AdmitAdultery.html
- steps/admit-adultery/AdmitAdultery.step.js
- steps/confirm-defence/ConfirmDefence.content.json
- steps/confirm-defence/ConfirmDefence.html
- steps/confirm-defence/ConfirmDefence.step.js
- steps/review-application/ReviewApplication.html
- steps/review-application/ReviewApplication.step.js
- test/e2e/pages/admitAdultery.js
- test/e2e/pages/confirmDefence.step.js
- test/e2e/pages/idam.step.js
- test/e2e/paths/adulteryJourney.js
- test/unit/steps/admitAdultery.test.js
- test/unit/steps/confirmDefence.test.js
- test/unit/steps/reviewApplication.test.js
- yarn.lock
Introducing a new screen flow for Adultery cases.
Tested manually, with unit tests and with functional tests using the new mock backend service.
> [PREVIEW] DIV-3203 Adultery admission question

- infrastructure/aat.tfvars
- infrastructure/preview.tfvars
Update google analytics id for testing
Fixes # DIV-3339
Locally - unit, e2e
> [PREVIEW] Update google analytics id for testing

- steps/consent-decree/ConsentDecree.content.json
- steps/consent-decree/ConsentDecree.step.js
- test/unit/steps/consentDecree.test.js
Small content change for 2yr separation journey.
Fixes # DIV-3221
> [PREVIEW] Update content for defence answers in CYA page

- steps/done/Done.content.json
- steps/done/Done.html
- test/unit/steps/done.test.js
Adds extra conditional content to done step for specific paths. 
Fixes # DIV-3367
Tested locally, unit.
> [PREVIEW] Done Step extra conditional content

- infrastructure/aat.tfvars
so that we redirect idam to the correct endpoint
Fixes #DIV-3489
> DIV-3489 - fixed additional_host_name for aat

- .gitignore
- package.json
- test/e2e/codecept.conf.js
- yarn.lock
> Adding new script that will add environment variables to functional test

- .gitignore
- Jenkinsfile_CNP
- config/custom-environment-variables.yml
- config/default.yml
- infrastructure/main.tf
- kubernetes/config.aat.yaml
- middleware/petitionMiddleware.js
- package.json
- test/e2e/codecept.conf.js
- test/e2e/codecept.smoke.conf.js
- test/e2e/helpers/JSWait.js
- test/e2e/helpers/caseConfigHelper.js
- test/e2e/helpers/caseHelper.js
- test/e2e/helpers/idamConfigHelper.js
- test/e2e/helpers/idamHelper.js
- test/e2e/pages/captureCaseIdAndPin.step.js
- test/e2e/pages/idam.step.js
- test/e2e/paths/happyPath.js
- test/resources/basic-divorce-session.json
- yarn.lock
> demo with latest master

- app.js
- package.json
- yarn.lock
Attempt to fix issue regarding CSS and other assets not loading (SSL / certificate auth fail)
> [PREVIEW] Apply new base URL for look and feel config

- app.js
> secure cookies

- steps/privacy-policy/PrivacyPolicy.content.json
- test/unit/services/caseOrchestration.test.js
- test/unit/steps/cookiesPolicy.test.js
- test/unit/steps/privacyPolicy.test.js
- test/unit/steps/termsAndConditions.test.js
Fix pipeline by increasing code coverage
> Incraese code coverage

- test/unit/helpers/courtInformation.js
- test/unit/steps/respond.test.js
- views/includes/sideMenuCourtDetails.html
> Added check on pobox and street for rcd info

- app.js
- config/default.yml
[DIV-3715 - AOS - no expires setting set on cookie](https://tools.hmcts.net/jira/browse/DIV-3715)
Add expires time for cookie
> add cookie expires

- infrastructure/main.tf
- infrastructure/variables.tf
To try to resolve missing style issue as suggested by devops
Fixes #DIV-3701
> DIV-3701 - Set website caching to never/0mb

- .gitignore
- README.md
- docker-compose.yaml
Updated readme to be in line with DN/PFE and added docker-compose file to make it cleaner to start RFE application
> [PREVIEW] Minor changes in readme and use of docker-compose

- README.md
- config/custom-environment-variables.yml
- config/default.yml
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/variables.tf
- kubernetes/config.aat.yaml
- middleware/redirectMiddleware.js
- mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer petitionerRedirect.mock
- mocks/services/case-orchestration/retrieve-aos-case/mock-petitioner-redirect.json
- mocks/steps/idamLogin/IdamLogin.content.json
- mocks/steps/idamLogin/IdamLogin.step.js
- mocks/steps/idamLogin/IdamLogin.template.html
- resources/mock.json
- steps/respond/Respond.step.js
- test/unit/middleware/redirectMiddleware.test.js
- test/unit/steps/respond.test.js
- test/w3cjs/index.js
- yarn.lock
[DIV-3509 - RFE - can access RFE using petitioner user](https://tools.hmcts.net/jira/browse/DIV-3509)
- Redirects user to DN if user is not respondent
> Redirect user to DN if user is not respondent

- infrastructure/prod.tfvars
Adds tracking id for page view tracking.
> Add google analytics tracking ID for prod

- config/default.yml
> increase time out

- package.json
- yarn.lock
> Remove unused dependancy 

- app.js
- middleware/feesAndPaymentsMiddleware.js
- middleware/healthcheck.js
- middleware/petitionMiddleware.js
- server.js
- services/caseOrchestration.js
- services/getCcdData.js
- services/logger.js
- services/redis.js
- steps/progress-bar/ProgressBar.step.js
- test/e2e/helpers/caseHelper.js
- test/unit/services/logger.test.js
[DIV-3703 - Print CCD & IDAM ID(?) in DN & AOS](https://tools.hmcts.net/jira/browse/DIV-3703)
> add idam id and ccd id to logs

- steps/financial-situation/FinancialSituation.content.json
https://tools.hmcts.net/jira/browse/DIV-4160
> DIV-4160: Removed redundant word

- steps/confirm-defence/ConfirmDefence.step.js
- steps/defend-financial-hardship/DefendFinancialHardship.step.js
Small fix for Two Year separation journey, and defending / changing answer. 
This is in addition to previous work to fix infinite re-direct loop;
Fixes # DIV-4159
* Hardware:
* JDK:
> DIV-4159 5yrs defended bug (fixes 2yr separation issue)

- test/unit/steps/confirmDefence.test.js
Adds couple tests for previous bug-fix [DIV-4159](https://tools.hmcts.net/jira/browse/DIV-4159)
Fixes # DIV-4217
Unit / manual
* Hardware:
* JDK:
> DIV-4217 Added testing for Confirm Defence re-direct bug

- app.js
- assets/scss/main.scss
- package.json
- yarn.lock
[DIV-4225](https://tools.hmcts.net/jira/browse/DIV-4225)
Fixes missing css styling from reform-pattern-library.
Manual test
> Add missing text reference css class

- assets/scss/main.scss
- package.json
- test/unit/steps/confirmDefence.test.js
- yarn.lock
> Update sandbox env with latest master code.

- .dockerignore
- .gitignore
- Dockerfile
- acb.tpl.yaml
- kubernetes/deployment.template.yaml
This PR leverages on layers re-use to reduce the the docker image build time in CI.
Jira ticket: https://tools.hmcts.net/jira/browse/CNP-1131
The PR CI shows a decrease of build time of the docker image (1:20-ish min)
> Activate ACR build, image multistaging and hmcts runtime user

- package.json
- yarn.lock
Before:
26 vulnerabilities found - Packages audited: 67820
Severity: 25 Low | 1 Moderate
Now:
No vulnerabilities
> DIV-4362: Force versions of underscore.string & braces to remove all vulns

- steps/co-respondent/cr-contact-details/CrContactDetails.step.js
- steps/co-respondent/cr-done/CrDone.content.json
- steps/co-respondent/cr-done/CrDone.html
- steps/co-respondent/cr-done/CrDone.step.js
- test/unit/steps/corespondent/crContactDetails.test.js
- test/unit/steps/corespondent/crDone.test.js
- yarn.lock
Created Done page for co respondent journey.
The page has dynamic content that is based on whether or not the costs of divorce are being claimed.
If costs are being claimed then its the end of the co-respondents journey, however if costs are being claimed then we inform them how to object.
> DIV-3991: Created CRDone page & dynamic content

- steps/co-respondent/cr-review-application/CrReviewApplication.content.json
- steps/co-respondent/cr-review-application/CrReviewApplication.html
- steps/respondent/review-application/ReviewApplication.content.json
- steps/respondent/review-application/ReviewApplication.html
- test/unit/steps/corespondent/crReviewApplication.test.js
- test/unit/steps/respondent/reviewApplication.test.js
If a co-respondent has been named then we show below detail in the what this means section of the mini petition:
“The co-respondent is the person the applicant claims the respondent committed adultery with.”
> Content added specific to co-respondent

- steps/capture-case-and-pin/CaptureCaseAndPin.content.json
- steps/capture-case-and-pin/CaptureCaseAndPin.html
https://tools.hmcts.net/jira/browse/DIV-4419
It's taking a while for users IDAM accounts to be associated with the relevant CCD case - up to two minutes. Below content added
"It may take a few minutes to finish setting up your account. Please don't leave this page or refresh it."
> Linking may take time - Info Content added

- steps/co-respondent/cr-contact-details/CrContactDetails.html
https://tools.hmcts.net/jira/browse/DIV-4473
Perform the Co-respondent Journey:
Email id should be in bold in the contact-details page
> Added bold style to email

- mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
- steps/respondent/review-application/ReviewApplication.content.json
- steps/respondent/review-application/ReviewApplication.html
- test/unit/steps/respondent/reviewApplication.test.js
Show additional adultery information if the petitioner states they got that information from someone else.
Fixes # DIV-4371
Unit tests were updated.
> DIV-4371 - Show additional adultery information got from another person

- package.json
- steps/respondent/review-application/ReviewApplication.content.json
- yarn.lock
Changed text from:
"Confirm that you have read your husband/wife's application"
to:
"Confirm that you have read the divorce application".
> DIV-4510: Fixed content on respondent review application page

- steps/privacy-policy/PrivacyPolicy.content.json
- steps/privacy-policy/PrivacyPolicy.html
Adding phrase to privacy page
Unit tests
> DIV-4386: Adding phrase to privacy page

- steps/respondent/review-application/ReviewApplication.content.json
- steps/respondent/review-application/ReviewApplication.html
[DIV-4387 - Add help content on Facts to AOS review application](https://tools.hmcts.net/jira/browse/DIV-4387)
- Update content based on prototype for mini petition
> update content for mini petition help section

- Jenkinsfile_CNP
- mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer co-respondent-amended-case.mock
- mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yesAdulteryAmendedCase.mock
- mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-amended-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-amended-case.json
- mocks/steps/idamLogin/IdamLogin.content.json
- mocks/steps/idamLogin/IdamLogin.step.js
- mocks/steps/idamLogin/IdamLogin.template.html
- steps/co-respondent/cr-respond/CrRespond.content.json
- steps/co-respondent/cr-respond/CrRespond.html
- steps/respondent/respond/Respond.content.json
- steps/respondent/respond/Respond.html
- test/unit/steps/corespondent/crDone.test.js
- test/unit/steps/corespondent/crRespond.test.js
- test/unit/steps/respondent/respond.test.js
- Updating title for landing pages for respondent and co-respondent.
- Enable prod deployments 
Unit tests and manual testing with mocks
> DIV-4485: changing landing page title for amended cases

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- config/ci.yml
- steps/co-respondent/cr-review-application/CrReviewApplication.content.json
- test/e2e/helpers/idamHelper.js
> DIV-4665 - renamed petitioner to applicant in co-respondent review page

- Jenkinsfile_nightly
- config/ci.yml
aat env variables for nightly pipeline
> aat env variables for nightly pipeline

- Jenkinsfile_nightly
> Add Vault values to nightly pipeline

- security.sh
- zapKnownIssues.xml
> Add exception file 

- assets/js/main.js
Ensure that every submit button is disabled after clicking it.
Fixes # DIV-4852
Manual testing
> DIV-4852 Add jquery hook to disable on submit click

- middleware/healthcheck.js
Introduce consistency in the naming of health checks
Fixes # [DIV-3999](https://tools.hmcts.net/jira/browse/DIV-3999)
> DIV-3999: Consolidate naming of responses in health check

- app.js
- config/default.yml
- mocks/services/case-orchestration/retrieve-aos-case/mock-2yr-separation-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case-two-dates.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-amended-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-amended-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingSubmittedAnswer.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingWaitingAnswer.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-coRespNotDefending.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-coRespTooLateToRespond.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-desertion-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-petitioner-redirect.json
- steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
- steps/co-respondent/cr-respond/CrRespond.content.json
- steps/respondent/progress-bar/ProgressBar.content.json
- steps/respondent/respond/Respond.content.json
- test/e2e/pages/co-respondent/crRespond.step.js
- test/e2e/pages/respondent/respond.step.js
- test/unit/steps/corespondent/crProgressBar.test.js
- test/unit/steps/corespondent/crRespond.test.js
- test/unit/steps/respondent/progressBar.test.js
- test/unit/steps/respondent/respond.test.js
[DIV-4863 - Respondent views CoE in their account](https://tools.hmcts.net/jira/browse/DIV-4863)
[DIV-4865 - Co-Respondent views CoE in their account](https://tools.hmcts.net/jira/browse/DIV-4865)
> add coe file to respondent and co-respondent

- steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
- steps/co-respondent/cr-progress-bar/CrProgressBar.html
- steps/respondent/progress-bar/ProgressBar.content.json
- steps/respondent/progress-bar/ProgressBar.html
- test/unit/steps/corespondent/crProgressBar.test.js
- test/unit/steps/respondent/progressBar.test.js
[DIV-5153 - Bold text on DN & AOS confirmation page](https://tools.hmcts.net/jira/browse/DIV-5153)
> DIV-5153 - Bold text on DN & AOS confirmation page

- package.json
- yarn.lock
> update npm dependancies 

- charts/div-rfe/values.aat.template.yaml
- charts/div-rfe/values.preview.template.yaml
- config/custom-environment-variables.yaml
- config/default.yml
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
- infrastructure/variables.tf
- middleware/petitionMiddleware.js
- middleware/redirectMiddleware.js
> DIV-5251: Redirect Respondent to DA if divorce is granted

- steps/respondent/review-application/ReviewApplication.html
This resolves a styling issue with the Jurisdiction paths on Review Application page.
[DIV-5327](https://tools.hmcts.net/jira/browse/DIV-5327)
* Hardware:
* JDK:
> Add gov-uk-body class when not a bullet list for jurisdictions

- steps/respondent/review-application/ReviewApplication.html
> Add Gov-Uk Body class when not a bullet list (#347)

- config/default.yml
- mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer aosAwaitingSol.mock
- mocks/services/case-orchestration/retrieve-aos-case/mock-aosAwaitingSol.json
- mocks/steps/idamLogin/IdamLogin.content.json
- mocks/steps/idamLogin/IdamLogin.step.js
- mocks/steps/idamLogin/IdamLogin.template.html
- steps/respondent/done/Done.content.json
- steps/respondent/done/Done.html
- steps/respondent/progress-bar/ProgressBar.content.json
- steps/respondent/progress-bar/ProgressBar.html
- steps/respondent/progress-bar/ProgressBar.step.js
- steps/respondent/progress-bar/sections/SolicitorOneCircleFilledInBold.html
- test/e2e/pages/common/idam.step.js
- test/e2e/pages/respondent/progressBar.js
- test/e2e/paths/respondent/progressBar.js
- test/unit/steps/respondent/done.test.js
- test/unit/steps/respondent/progressBar.test.js
https://tools.hmcts.net/jira/browse/DIV-4900
> Div 4900 progress bar page for aos awaiting sol

- test/e2e/helpers/idamHelper.js
to reduce Gov notify failures changed the domain name
> change domain

- Jenkinsfile_CNP
- infrastructure/preview.tfvars
Fixes feature flag issue on pipeline
> Ensure Jenkins AAT env is feature flagged off

- test/e2e/paths/respondent/happyPath.js
- yarn.lock
> add more wait to crOss browser tests

- test/crossbrowser/supportedBrowsers.js
- test/e2e/pages/common/captureCaseIdAndPin.step.js
- test/e2e/pages/respondent/agreeToPayCosts.step.js
- test/e2e/pages/respondent/checkYourAnswers.step.js
- test/e2e/pages/respondent/chooseAResponse.step.js
- test/e2e/pages/respondent/contactDetails.step.js
- test/e2e/pages/respondent/done.step.js
- test/e2e/pages/respondent/jurisdiction.step.js
- test/e2e/pages/respondent/legalProceedings.step.js
- test/e2e/pages/respondent/progressBar.js
- test/e2e/pages/respondent/respond.step.js
- test/e2e/pages/respondent/reviewApplication.step.js
- test/e2e/paths/respondent/happyPath.js
Mac Firefox and Safari in Sauce labs are causing some issues in waits and element identification.
> Fix cross browser tests

- package.json
- steps/respondent/check-your-answers/CheckYourAnswers.html
- steps/respondent/review-application/ReviewApplication.html
- views/includes/sideMenu.html
- views/includes/sideMenuCoRespondent.html
- yarn.lock
[DIV-4671 - Accessibility [A] - Missing heading levels](https://tools.hmcts.net/jira/browse/DIV-4671)
- Use latest look and feel which updates CYA
- update side panel headings
- update review application template
> Fix heading structure

- Jenkinsfile_CNP
- package.json
[DIV-5634 - Update vault definitions for DN, RFE and PFE](https://tools.hmcts.net/jira/browse/DIV-5634)
> DIV-5634 - Update vault definitions for DN, RFE and PFE

- test/w3cjs/index.js
our requests to validate html keep failing so this PR adds a temporary solution to retry the request up to three times if it fails
> retry request to validate html

- charts/div-rfe/values.preview.template.yaml
[Fix IDAM chart tags syntax to allow for post-PR scripts](https://tools.hmcts.net/jira/browse/DIV-5694)
> DIV-5694 Fix IDAM chart tags syntax

- charts/div-rfe/values.preview.template.yaml
Need to revert chart config as it causes issues in whitelisting.
> Revert IDAM tag

- Jenkinsfile_CNP
- infrastructure/aat.tfvars
To allow testing before release
Fixes #DIV-3877
> DIV-3877 - enable respondent solicitor feature in AAT

- Jenkinsfile_CNP
- config/ci.yml
> DIV-3877 - enable respondent solicitor feature in AAT tests

- infrastructure/main.tf
Stop using deprecated moj .tf modules
DIV-5750
- [y] Bug fix (non-breaking change which fixes an issue)
* Hardware:
* JDK:
> Use hmcts/cnp modules

- steps/co-respondent/cr-review-application/CrReviewApplication.html
- steps/respondent/jurisdiction/Jurisdiction.html
- steps/respondent/review-application/ReviewApplication.html
To be merged into Dom's branch if approved. pending UX. #375
> Add aria-labels for what this means expandable sections

- infrastructure/main.tf
> Fix deprecated infra error

- charts/div-rfe/values.aat.template.yaml
- charts/div-rfe/values.preview.template.yaml
- config/default.yml
- infrastructure/aat.tfvars
- infrastructure/variables.tf
Merge on 26/09
Fixes #DIV-5040
> DIV-5040 - turn on feature flag for respondent solicitor

- infrastructure/prod.tfvars
[DIV-5756 Enable webchat on live environment](https://tools.hmcts.net/jira/browse/DIV-5756)
- Add live webchat environment variables
> Webchats - add live environment variables

- charts/div-rfe/values.preview.template.yaml
- config/default.yml
- infrastructure/variables.tf
[DIV-5756 - Enable webchat on live environment](https://tools.hmcts.net/jira/browse/DIV-5756)
- Remove chart specific config
- Set webchat default to true
- Set webchat default on true for PROD and AAT environments
> DIV-5756 - Enable webchat on live environment

- services/setupSecrets.js
PFE has it as host, copied it over and didn't check 🤦‍♂
> Fix typo for AKS

- app.js
- infrastructure/variables.tf
- steps/co-respondent/cr-done/CrDone.content.json
- steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
- steps/respondent/done/Done.content.json
- steps/respondent/progress-bar/ProgressBar.content.json
- yarn.lock
https://tools.hmcts.net/jira/browse/DIV-5608
Simply updated URLS to new Smart Survey URLS
- Swapped to new Smart Survey URLs for in-page feedback and done page
- Added HTML back into Done page to request feedback etc
- Deleted unused infra vars
> DIV-6508: Swapped to new smart survey urls

- security.sh
https://tools.hmcts.net/confluence/display/RQA/Integrate+with+Glue+for+ignoring+false+postivies?focusedCommentId=1186104637&refresh=1570545877813#comment-1186104637
> python2 and python3 compatibility issue on nightly pipeline

- security.sh
https://tools.hmcts.net/confluence/display/RQA/Integrate+with+Glue+for+ignoring+false+postivies?focusedCommentId=1186104637&refresh=1570545877813#comment-1186104637
> To Add Glue suppression file suggested

- README.md
- config/ci.yml
- config/default.yml
- infrastructure/preview.tfvars
- infrastructure/variables.tf
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Manual test.
> Switching off respondent solicitor feature-toggle

- charts/div-rfe/values.preview.template.yaml
- infrastructure/variables.tf
- test/w3cjs/index.js
> client_id variable removed

- Jenkinsfile_CNP
- charts/div-rfe/Chart.yaml
- charts/div-rfe/requirements.yaml
https://tools.hmcts.net/jira/browse/RPET-242
> RPET-242-remove-deprecated-method

- steps/respondent/financial-situation/FinancialSituation.content.json
https://tools.hmcts.net/jira/browse/WLA-566
> WLA-566: Amend Welsh Yes/No answers

- steps/respondent/language-preference/languagePreference.content.json
- steps/respondent/language-preference/languagePreference.html
https://tools.hmcts.net/jira/browse/WLA-559
> WLA-559: Amend copy on Language question

- steps/co-respondent/cr-review-application/CrReviewApplication.content.json
- steps/respondent/review-application/ReviewApplication.content.json
https://tools.hmcts.net/jira/browse/WLA-564
> WLA-564: Add adultery explanation in Welsh

- server.js
- services/setupSecrets.js
https://tools.hmcts.net/jira/browse/RPET-299
> RPET-299-app-insights-config

- steps/respondent/choose-a-response/ChooseAResponse.content.json
- steps/respondent/defend-financial-hardship/DefendFinancialHardship.content.json
- steps/respondent/legal-proceedings/LegalProceedings.content.json
- steps/respondent/review-application/ReviewApplication.content.json
https://tools.hmcts.net/jira/browse/WLA-591
> WLA-591: Welsh copy amends

- package.json
- yarn.lock
> bump dependencies to remove CVE's

- steps/equality/Equality.step.js
- test/unit/steps/equality/equality.test.js
https://tools.hmcts.net/jira/browse/PCQ-591
Add CORESPONDENT actor type.
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
> PCQ-591: Add CORESPONDENT actor type

- steps/respondent/language-preference/LanguagePreference.step.js
- test/unit/steps/respondent/languagePreference.test.js
https://tools.hmcts.net/jira/browse/RPET-367
> RPET-367-Respondent-2-year-separation-and-Adultery-questions-missing

- config/default.yml
- middleware/petitionMiddleware.js
- mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer serviceApplicationNotApproved.mock
- mocks/services/case-orchestration/retrieve-aos-case/mock-serviceApplicationNotApproved.json
- mocks/steps/idamLogin/IdamLogin.content.json
- mocks/steps/idamLogin/IdamLogin.step.js
- mocks/steps/idamLogin/IdamLogin.template.html
- test/unit/middleware/petitionMiddleware.test.js
IF a case is in the state 'ServiceApplicationNotApproved'
AnD the respondent logs into RFE
THEN they should not be redirected to another app (DN, DA, PFE)
AND they should see a landing page
AND be able to complete their Acknowledge of Service response
Fixes https://tools.hmcts.net/jira/browse/DIV-6531
* Hardware:
* JDK:
> Div-6531: Handle state ServiceApplicationNotApproved

- package.json
- yarn.lock
Address CVE Issues
[RPET-361](https://tools.hmcts.net/jira/browse/RPET-361)
* Hardware:
* JDK:
> RPET-361: fix CVE issues

- package.json
Made a change in Package.json file to fix the Pa11y Reporting.
* Hardware:
* JDK:
> Fixed Pa11y Reporting

- test/a11y/index.js
Added welsh check for Respondent Accessibility test.
> Added welsh check for respondent accessibility test

- Jenkinsfile_nightly
- package.json
- test/e2e/pages/common/equality.js
Respondent Nightly Pipeline setup
https://tools.hmcts.net/jira/browse/TA-247
> TA-247 Respondent Nightly Setup

- config/default.yml
Reduce timeouts for crossbrowser tests to avoid failures slowing down the whole pipeline.
This is needed to avoid exceeding the Crossbrowser Jenkins step max runtime.
Fixes # https://tools.hmcts.net/jira/browse/TA-77
* Hardware:
* JDK:
> Reduce crossbrowser test timeouts

- package.json
- yarn.lock
Vulnerability fix, updating axios. version
> DIV-6654: Update to axios version

- test/e2e/paths/respondent/behaviourHappyPath-en-cy.js
- test/e2e/paths/respondent/desertionJourneyHappyPath-en-cy.js
Lengthen wait time and remove magic numbers
> DIV-6735: Fix functional tests

- test/e2e/paths/respondent/desertionJourneyHappyPath-en-cy.js
Change `numberOfTimesRetried` to `amountOfTimesToRetry`
> DIV-6735-Update variable name

- audit.json
Link to failed build:
https://build.platform.hmcts.net/job/HMCTS_Nightly_DIV/job/div-respondent-frontend/job/master/298/artifact/functional-output/activescan.html#high
> DIV-6731 10017-Cross Domain suppression

- Jenkinsfile_CNP
- audit.json
- security.sh
https://tools.hmcts.net/jira/browse/RPET-656
> RPET-656: nightly build update

- test/e2e/helpers/idamHelper.js
I've noticed removing idam accounts in e2e test is quite frequently a reason of broken build.
Lets try to do it 3 times before it breaks the build.
> Add retry for removing users from idam

- README.md
Noticed that Git didn't quite render heading the way the IDE render added a required space
> DIV-6948: Minor markup style update

- test/e2e/codecept.conf.js
https://tools.hmcts.net/jira/browse/DFR-145
Bug fix
- [ X] Bug fix (non-breaking change which fixes an issue)
* Hardware:
* JDK:
- [X ] My code follows the style guidelines of this project
> DFR-145 Adding Chrome args to fix the master pipeline.

- package.json
- yarn.lock
> Bumping moment

- assets/locale/locale_en-GB.json
Update contactCenterClosed value
> DFR-1045 Update contactCenterClosed text

- charts/div-rfe/Chart.yaml
- charts/div-rfe/values.yaml
https://tools.hmcts.net/jira/browse/DTSSE-1395
> Autoscaling

- package.json
- yarn.lock
> Update deps 01 08 22
