hmcts/div-respondent-frontend

- test/w3cjs/index.js
To unblock build.
W3C HTML validator rules changes, preventing `<h*>` elements to be inside
`<legend>`. See https://github.com/hmcts/look-and-feel/issues/100
Fixes #DIV-3528
N/A
> DIV-3528 - temporarily ignored W3C HTML validation tests

- infrastructure/aat.tfvars
We get a "Too many (2) hostnames in the default DNS zone. Limit is 1"
error that might be due to this (duplicate hostname entries)
We changed this back in October 29 but we think it never took effect at the time and only surfaced last Friday when we deleted the env and recreated it
##
> Change additional_host_name to be something other than the default

- middleware/healthcheck.js
- test/unit/middleware/healthcheck.test.js
Recently, DevOps have introduced a proxy requirement for this endpoint (ticket RDO-3077)
The healthcheck module currently doesn't support a proxy, so we're removing this temporarily.
Fixes #DIV-3766
> DIV-3766 - remove "idam-authentication" (web app) health check

- app.js
[DIV-3646 - Slow pages loads could be result of getting IDAM credentials on every request ( including assets )](https://tools.hmcts.net/jira/browse/DIV-3646)
Move IDAM auth after assets in effort to speed up application.
> Move idam auth to after assets

- app.js
- mocks/services/case-orchestration/retrieve-aos-case/mock-2yr-separation-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-petitioner-redirect.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-started-response.json
- steps/check-your-answers/CheckYourAnswers.html
[DIV-3861](https://tools.hmcts.net/jira/browse/DIV-3861)
CSRF is currently not active on RFE. It is a feature in OPP and Look and Feel and just needs to be enabled.
Also local testing fails because mocked respondent email address does not match the mock IDAM user email in certain scenarios. To fix this, modified the mock respondent email addresses to match the IDAM mock user email.
All tests pass. Manual test pass, manually modifying the csrf fails the page as expected, so all good thus far.
* Hardware:
* JDK:
> Enable CSRF and fix local mocks for local testing

- package.json
- yarn.lock
[DIV-3859 - cross site scripting is possible on AOS and DN Journeys](https://tools.hmcts.net/jira/browse/DIV-3859)
With the caret, the latest OPP should get used (per deploy), however, we should enforce the minimum version for security reasons probably, so bumping up the version.
> Enforce minimum version of OPP for santisation

- test/e2e/helpers/idamHelper.js
- test/unit/steps/done.test.js
https://tools.hmcts.net/jira/browse/DIV-3830
Replace ‘email@email.com’ from emails from integration tests as it is spamming notification service when we run integration tests. 
Created new HMCTS Divorce gmail account for testing with unique users
> DIV-3830: Changed simulate email address with valid gmail for int tests

- infrastructure/main.tf
- infrastructure/variables.tf
Fetch App Insights instrumentation key from Key Vault secrets instead of using App Service environment variables. This process is managed by [CNP module](https://github.com/hmcts/cnp-module-webapp/blob/master/main.tf#L66) for deploying into Azure.
Fixes # DIV-3853
Manual testing for checking that PR in PREVIEW is pointing to AAT App Insights.
> [PREVIEW] DIV-3853 Apply infra for app insights config

- package.json
- test/unit/steps/agreeToPayCosts.test.js
- test/unit/steps/consentDecree.test.js
- test/unit/steps/contactDetails.test.js
- test/unit/steps/defendFinancialHardship.test.js
- test/unit/steps/jurisdiction.test.js
- test/unit/steps/legalProceedings.test.js
- yarn.lock
[DIV-3794 - OPP - AddAnother is broken from our 4.X.X release](https://tools.hmcts.net/jira/browse/DIV-3794)
This PR reverts a change made a while ago to swap dots for hyphens for input names. This was due to a bug in GOVUK elements which has now been resolved.
The reason we are reverting is because the previous change from dots to hyphens broke the Add Another functionality of One Per Page
> Revert dot to hyphen references in OPP

- sonar-project.properties
Excluding Duplicate checks as respondent and co-respondent have similar data
Sonar scan is failing on master rfe but on AKS it is successful.
> Sonar Duplicate checks excluded

- mocks/services/case-orchestration/retrieve-aos-case/case-progressed/awaiting-answer.json
- mocks/services/case-orchestration/retrieve-aos-case/case-progressed/defended.json
- mocks/services/case-orchestration/retrieve-aos-case/case-progressed/no-aos.json
- mocks/services/case-orchestration/retrieve-aos-case/case-progressed/not-defended.json
- steps/respondent/consent-decree/ConsentDecree.step.js
- steps/respondent/progress-bar/ProgressBar.step.js
- test/unit/services/googleAnalytics.test.js
- test/unit/steps/respondent/consentDecree.test.js
- test/unit/steps/respondent/progressBar.test.js
[DIV-4267](https://tools.hmcts.net/jira/browse/DIV-4267)
RespDefendsDivorce is an old CCD field that should no longer be used. However it is currently used in the Separation-2-Year Journey. This PR replaces it with the newer RespWillDefendDivorce field
> Change deprecated RespDefendsDivorce to te RespWillDefendDivorce field

- steps/respondent/review-application/ReviewApplication.content.json
- steps/respondent/review-application/ReviewApplication.html
- test/unit/steps/respondent/reviewApplication.test.js
https://tools.hmcts.net/jira/browse/DIV-4359
If the field D8ReasonForDivorceDesertionAgreed = 'Yes', then additional text ("The applicant stated that the respondent left without their agreement.") should show in the mini-petition.
> Desertion agreement details added in mini-petition

- Jenkinsfile_CNP
- test/e2e/helpers/idamHelper.js
As NODE_ENV=ci was moved from `after('test')` to before every functional stage, this was missed
Fixes #DIV-4665
> DIV-4665 - set NODE_ENV in master pipeline for AAT testes

- middleware/petitionMiddleware.js
When investigating this live issue this warning message was a red herring to me. This was being displayed even in the normal flow of the app (AOSStarted cases and 200 HTTP response).
I hope to save other people's time in the future by lowering this.
I've raised a ticket to handle other error responses in this middleware component. It's DIV-4697. 
No tests needed.
> DIV-4663: Lowering severity in log message. This is actually the normal flow.

- middleware/petitionMiddleware.js
- test/unit/middleware/petitionMiddleware.test.js
https://tools.hmcts.net/jira/browse/DIV-4474
When the case is in aos awaiting state  if case is found associated with resp email address, we should redirect to Capture case and pin page
> Redirect to capture pin page when case state is aos awaiting

- steps/respondent/progress-bar/ProgressBar.step.js
Use warning log, not error log
https://tools.hmcts.net/jira/browse/DIV-4698
very easy change - use warning log instead of error log as it's misleading.
> DIV-4698: use warnWithReq in ProgressBar.step.js

- Dockerfile
- acb.tpl.yaml
> Next monday we will be changing the registry the pipeline will be pushing to by default
> the registry will be changing from:
> hmcts => hmctspublic
> you will no longer need to log in to pull your images (because it is a public registry, same as dockerhub)
> the name of the "repo" will change from
> "hmcts/product-component" => "product/component"
> Update to use the public HMCTS docker registry

- config/default.yml
- mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer coRespDNPronouncedWithCosts.mock
- mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer coRespDNPronouncedWithoutCosts.mock
- mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-dnPronouncedWithCosts.json
- mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-dnPronouncedWithoutCosts.json
- mocks/steps/idamLogin/IdamLogin.content.json
- mocks/steps/idamLogin/IdamLogin.step.js
- mocks/steps/idamLogin/IdamLogin.template.html
- steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
- steps/co-respondent/cr-progress-bar/CrProgressBar.html
- steps/co-respondent/cr-progress-bar/CrProgressBar.step.js
- steps/respondent/progress-bar/ProgressBar.html
- test/e2e/pages/co-respondent/crProgressBar.js
- test/e2e/pages/common/idam.step.js
- test/e2e/paths/co-respondent/progressBar.js
- test/unit/steps/corespondent/crProgressBar.test.js
[DIV-4892 - Co-Respondent landing page with Cost Order](https://tools.hmcts.net/jira/browse/DIV-4892)
- Shows Costs order file if co-respondent paying
- Shows specific content if state DNPronounced and co-respondent paying costs
[DIV-5123 - Co-Respondent landing page without Cost Order](https://tools.hmcts.net/jira/browse/DIV-5123)
- Does not show any new content
- Does not show costs order file
in addition it fixes some old styles missed in old gov.uk design updates
> DIV-4892 - Co-Respondent landing page with Cost Order

- middleware/healthcheck.js
- test/unit/middleware/healthcheck.test.js
liveness is calling health currently and causing too many health checks on apps.
https://www.respond-divorce.service.gov.uk/health/liveness
> fix liveness

- Jenkinsfile_nightly
- bin/run-crossbrowser-tests.sh
- test/crossbrowser/supportedBrowsers.js
- test/e2e/helpers/JSWait.js
- test/e2e/pages/co-respondent/crChooseAResponse.step.js
- test/e2e/pages/co-respondent/crReviewApplication.step.js
- test/e2e/pages/common/captureCaseIdAndPin.step.js
- test/e2e/pages/common/equality.js
- test/e2e/paths/co-respondent/adulteryJourney.js
- test/e2e/paths/respondent/2yrSeparationHappyPath-en-cy.js
- test/e2e/paths/respondent/5yrSeparationHappyPath-en-cy.js
- test/e2e/paths/respondent/behaviourHappyPath-en-cy.js
- test/e2e/paths/respondent/desertionJourneyHappyPath-en-cy.js
- test/e2e/saucelabs.conf.js
This change:
- turns back on the crossbrowser tests in the nightly pipeline
- fixes an e2e test wait where the Welsh content has a NBSP character that browsers handle differently, and can cause test flakiness
- adds a workaround to `completePCQs()` for the current bug (https://tools.hmcts.net/jira/browse/RPET-632) where PCQ pages always display in English on AAT regardless of the language of the test
- reduces crossbrowser-specific waits now that steps wait better for page content
Fixes # https://tools.hmcts.net/jira/browse/TA-77
This has been tested locally for both Puppeteer functional and Webdriver crossbrowser tests, and in the PR pipeline.
* Hardware:
* JDK:
> Feature(TA-77): Run crossbrowser tests nightly (2)

- test/crossbrowser/supportedBrowsers.js
Increase screenResolution for Windows Firefox crossbrowser tests, to improve test stability when running in Saucelabs.
This has been tested nightly and now results in pretty consistent success rates for the Windows Firefox crossbrowser tests.
https://build.platform.hmcts.net/job/HMCTS_Nightly_DIV/job/div-respondent-frontend/view/change-requests/job/PR-509/4/artifact/functional-output/firefox_075214228fa4215246d1f1fb169ffa98_1/mochawesome.html
* Hardware:
* JDK:
> Feature: Increase screenResolution for Windows Firefox crossbrowser tests

- test/e2e/pages/co-respondent/crRespond.step.js
Updates the c value of e2e test step crRespond.step.js to be unique to the expected page, instead of the title "Respond to a Divorce" which appears in the top bar on _every_ page.
This solves an issue with Safari crossbrowser test, where Safari updates the URL bar with the new URL before the page has actually changed (it's the only browser to do this). This passes the `waitInUrl()` step, and so the test then waits for the expected page title which happens to match on _any_ page in the respondent journey because "Respond to a Divorce" is in the top nav of the service. This results in the `waitForText()` step passing and the test trying to continue, all before the new page has actually loaded, and so the test fails.
Now the text is unique to the new page, so the waiting mechanism works …
> Crossbrowser improvement: Update the waitForText() value to be unique to the expected page

- config/default.yml
- core/utils/petitionHelper.js
- middleware/petitionMiddleware.js
- steps/divorce-application-processing/DivorceApplicationProcessing.content.json
- steps/divorce-application-processing/DivorceApplicationProcessing.html
- steps/divorce-application-processing/DivorceApplicationProcessing.step.js
- test/unit/core/utils/petitionerHelper.test.js
- test/unit/middleware/petitionMiddleware.test.js
- test/unit/steps/divorceApplicationProcessing.test.js
Implementing a landing page for RFE when case is either `AwaitingReferralPaymemt` or `GeneralComsiderationComplete`. Original implementation was to reuse similar existing page on DN but the authtoken from RFE does not seem to work when trying to use it to retrieve case data on DN.
> DIV-6654: Map general referral states on Respondent apps
